[package]
name = "Kyoka"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
dotenv = "0.15.0"
eframe = "0.31.1"
egui = "0.31.1"
fefix = { version = "0.7.0", features = ["fix44"] }
log = "0.4.27"
pretty_env_logger = "0.5.0"
rand = "0.9.1"
